version: '3'
services:
  realtime-runner:
    build:
      context: .
      dockerfile: dev.Dockerfile
      platforms:
        - "linux/amd64"
    volumes:
      - ./realtime:/usr/src/app/realtime
      - ./examples:/usr/src/app/examples
      - ./functions:/usr/src/app/functions
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PYTHON_ENV: development
      ADAPT_API_KEY: eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..Qw_ekhQWENVgHgFASUIadg.NUJr1H4-hnhynpb1JjC9M-kIvk7CoNj3BcGCyu1l4PiBHGwsZdbL1Fbj4cwbdZO_qcSWFV_eNAjsbbf_.ql_o38KLU_LHXcoDZvL5Og
      ADAPT_ENDPOINT: http://host.docker.internal:3000/deploy
    stdin_open: true  # Keep stdin open even if not attached
    tty: true  # Allocate a pseudo-TTY

